version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: fruit_db
    environment:
      POSTGRES_DB: fruits_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fruit_network
    restart: unless-stopped

  # Backend API
  backend:
    build: ./backend
    container_name: fruit_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fruits_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - fruit_network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build: ./frontend
    container_name: fruit_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - fruit_network
    restart: unless-stopped

  # Prometheus Monitoring
  prometheus:
    build: ./prometheus
    container_name: fruit_prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - backend
    networks:
      - fruit_network
    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:

networks:
  fruit_network:
    driver: bridge
