apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fruit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: anupsharma329/backend:g1.2
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fruit-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort