name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-22.04
    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install sonar-scanner
        run: |
          npm install -g sonar-scanner@latest

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          npm test || true

      - name: Run frontend tests
        run: |
          cd frontend
          npm test || true

      - name: SonarQube Scan (Backend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd backend
          npx sonar-scanner \
            -Dsonar.projectKey=backend \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://6f86b207f300.ngrok-free.app \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.scm.disabled=true


      - name: SonarQube Scan (Frontend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd frontend
          npx sonar-scanner \
            -Dsonar.projectKey=frontend \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://6f86b207f300.ngrok-free.app \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}



      - name: Build Docker images
        run: |
          docker build -t anupsharma329/backend:g1.2 ./backend
          docker build -t anupsharma329/frontend:g1.2 ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push backend image
        run: docker push anupsharma329/backend:g1.2

      - name: Push frontend image
        run: docker push anupsharma329/frontend:g1.2





      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8/namespace.yml
          kubectl apply -f k8/backend-deployment.yml
          kubectl apply -f k8/frontend-deployment.yml
          kubectl apply -f k8/grafana-deployment.yml
          kubectl apply -f k8/prometheus-deployment.yml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      # Add deployment steps here if needed
